WordsAndSynonyms/Models/IdentityModels.cs
using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace WordsAndSynonyms.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DefaultConnection", throwIfV1Schema: false)
        {
        }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }
    }
}

WordsAndSynonyms/Models/WordsAndSynonyms.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsAndSynonyms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WordsEntities : DbContext
    {
        public WordsEntities()
            : base("name=WordsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<word> words { get; set; }
    }
}

WordsAndSynonyms/Models/WordsAndSynonyms.Designer.cs
// T4 code generation is enabled for model 'F:\SoruceCode\WordsAndSynonyms\WordsAndSynonyms\Models\WordsAndSynonyms.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

WordsAndSynonyms/Models/WordsAndSynonyms.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


WordsAndSynonyms/Models/word.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsAndSynonyms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class word
    {
        public int wordId { get; set; }
        public string word1 { get; set; }
        public string result { get; set; }
        public Nullable<System.DateTime> updatedTime { get; set; }
    }
}

WordsAndSynonyms/Controllers/BackendController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WordsAndSynonyms.Models;
using WordsAndSynonyms.Provider;

namespace WordsAndSynonyms.Controllers
{
	public class BackendController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public JsonResult loadDb()
		{
			String path = HttpContext.Server.MapPath("/Dependencies/files/words_dictionary.json");

			try
			{

				using (StreamReader r = new StreamReader(path))
				{
					string file = r.ReadToEnd().Replace("\n", "");
					string[] words = file.Split(',');
					using (var crud = new Crud())
					{
						word newWord;
						foreach (var text in words)
						{
							if (text.StartsWith("x"))
							{
								newWord = new word()
								{
									updatedTime = DateTime.Now,
									word1 = text
								};
								crud.updateWords(newWord);
							}
						}
					}
				}
			}
			catch (Exception ex)
			{
				return Json( new
				{
					success = false,
				}, JsonRequestBehavior.AllowGet);
			}

			return Json(new
			{
				success = true,
			}, JsonRequestBehavior.AllowGet);

		}

	}
}

WordsAndSynonyms/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WordsAndSynonyms.Provider;
using System.Web.Script.Serialization;
using Newtonsoft.Json.Linq;

namespace WordsAndSynonyms.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public JsonResult loadSuggestions(string word)
		{
			JObject jsonObject;
			List<object> bd = new List<object>();

			try
			{
				using (var crud = new Crud())
				{
					var suggestions = crud.getWord(word);
					jsonObject = new JObject();

					if (suggestions != null)
					{

						foreach (var item in suggestions)
						{

							jsonObject[item] = null;

						}
					}
				}
			}
			catch (Exception ex)
			{
				return Json(new
				{
					success = false,
				}, JsonRequestBehavior.AllowGet);
			}

			return Json(new
			{
				success = true,
				data = Newtonsoft.Json.JsonConvert.SerializeObject(jsonObject)
			}, JsonRequestBehavior.AllowGet);

		}
	}


}

WordsAndSynonyms/Views/Backend/Index.cshtml
@{
	ViewBag.Title = "BackEnd";
}
<link href="~/Dependencies/css/backend.css" rel="stylesheet" />
<div id="modal1" class="modal">
	<div class="modal-content">
		<h4>Confirmation</h4>
		<p>Are you sure you want to start the syncing process?</p>
	</div>
	<div class="modal-footer">
		<a class="modal-close waves-effect waves-green btn-flat">Cancel</a>
		<a id="confirmUpload" href="#!" class="modal-close waves-effect waves-green btn-flat">Yes</a>
	</div>
</div>
<nav>
	<div class="nav-wrapper">
		<a href="#" class="brand-logo">Logo</a>
		<ul id="nav-mobile" class="right">
			<li class="flex"><i class="material-icons prefix">featured_play_list</i><a href="sass.html">PlayList</a></li>
			<li class="flex"><i class="material-icons prefix">home</i><a href="@Url.Action("Index", "Home")">Homepage</a></li>
		</ul>
	</div>
</nav>
<div class="container page">
	<div class="content">
		<h3 class="row flow-text">
			Press the button to load the Dictionary.
		</h3>
		<div class="row">
			<a id="loadDictionary" class="waves-effect waves-light pulse btn-large"><i class="material-icons right">cloud</i>Load</a>
		</div>
		<div class="row">
			<div id="fileLoader" class="preloader-wrapper big">
				<div class="spinner-layer spinner-blue">
					<div class="circle-clipper left">
						<div class="circle"></div>
					</div><div class="gap-patch">
						<div class="circle"></div>
					</div><div class="circle-clipper right">
						<div class="circle"></div>
					</div>
				</div>

				<div class="spinner-layer spinner-red">
					<div class="circle-clipper left">
						<div class="circle"></div>
					</div><div class="gap-patch">
						<div class="circle"></div>
					</div><div class="circle-clipper right">
						<div class="circle"></div>
					</div>
				</div>

				<div class="spinner-layer spinner-yellow">
					<div class="circle-clipper left">
						<div class="circle"></div>
					</div><div class="gap-patch">
						<div class="circle"></div>
					</div><div class="circle-clipper right">
						<div class="circle"></div>
					</div>
				</div>

				<div class="spinner-layer spinner-green">
					<div class="circle-clipper left">
						<div class="circle"></div>
					</div><div class="gap-patch">
						<div class="circle"></div>
					</div><div class="circle-clipper right">
						<div class="circle"></div>
					</div>
				</div>
			</div>
			<div class="flow-text wait hide">Please Wait...</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function () {

		$('#modal1').modal();
		let button = $('#loadDictionary');
		let loader = $('#fileLoader');
		let wait = $('.wait');

		$("#loadDictionary").click(function (e) {
			$('#modal1').modal('open');
		});

		function actions() {
			button.toggleClass('pulse');
			loader.toggleClass('active');
			button.toggleClass('disabled');
			wait.toggleClass('hide');
		}

		$("#confirmUpload").click(function (e) {
			let url = '@Url.Action("loadDb", "Backend")';

			actions();

			$.ajax({
				url: url,
				type: 'get',
				cache: false,
				success: function (data) {
					actions();
					var toastHTML = '<span>Your data has been synced successfully</span><button onclick="cloasToast()" class="btn-flat toast-action">Close</button>';
					M.toast({ html: toastHTML });
				},
				error: function (err) {
					actions();
					var toastHTML = '<span>Some error Occurred</span><button onclick="cloasToast()" class="btn-flat toast-action">Close</button>';
					M.toast({ html: toastHTML });
				}
			});
		});
	});

	function cloasToast() {
		M.Toast.dismissAll();
	}

</script>

WordsAndSynonyms/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Search";
}
<link href='https://fonts.googleapis.com/css?family=Mansalva' rel='stylesheet' type='text/css'>
<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.2.0/anime.js"></script>
<link href="~/Dependencies/css/Index.css" rel="stylesheet" />
<nav>
	<div class="nav-wrapper">
		<a href="#" class="brand-logo">Logo</a>
		<ul id="nav-mobile" class="right">
			<li class="flex"><i class="material-icons prefix">featured_play_list</i><a href="sass.html">PlayList</a></li>
			<li class="flex"><i class="material-icons prefix">perm_data_setting</i><a href="@Url.Action("Index", "Backend")">Backend</a></li>
		</ul>
	</div>
</nav>
<div class="container page">
	<div class="row logo">
		<div class="ml2">WORDS</div>
	</div>
	<div class="row search">
		<div class="input-field s12 m12 l12" style="width:100%">
			<i class="material-icons prefix">search</i>
			<input type="text" id="autocomplete-input" class="autocomplete">
			<label for="autocomplete-input">Search...</label>
		</div>
	</div>
</div>

<script>

	$(document).ready(function () {

		$(".autocomplete").each(function () {
			let self = this;
			$(this).autocomplete();
			var instance = M.Autocomplete.getInstance(this);
			instance.options.minLength = 2
			$(this).on("input change", function () {
				var textValue = $('#autocomplete-input')[0].value;
				//var url = `https://wordsapiv1.p.mashape.com/words/${textValue}`
				let url = '@Url.Action("loadSuggestions", "Home")';
				if (textValue.trim().length >= 2) {
					$.ajax({
						url: url,
						type: 'get',
						cache: false,
						data: { word:textValue },
						//headers: { "X-Mashape-Key": "ea39a00b6amsh04d5bbc72fb3da0p1b57e5jsn5f53f63651a9", "Accept": "application/json" },
						success: function (data) {
							if (Object.keys(data).length !== 0 && data.constructor === Object) {
								$(self).autocomplete("updateData", JSON.parse(data.data));
							}
						},
						error: function (err) {
							console.log(err);
						}
					});
				}
			});
		});

		//var el = document.querySelector('.my-text');

		//var options = {
		//	size: 100,         // Font size, defined by the height of the letters (pixels)
		//	weight: 10,         // Font weight (pixels)
		//	rounded: false,    // Rounded letter endings
		//	color: '#5F6062',  // Font color
		//	duration: 1,       // Duration of the animation of each letter (seconds)
		//	delay: [0, 0.05],  // Delay animation among letters (seconds)
		//	fade: 0.5,         // Fade effect duration (seconds)
		//	easing: d3_ease.easeCubicInOut.ease,   // Easing function
		//	individualDelays: false,
		//};

		//var myText = new Letters(el, options);
		//var newOptions = {
		//	duration: 2,
		//	delay: 0.2,
		//	fade: 1,
		//	easing: d3_ease.easeCircleInOut.ease,
		//	individualDelays: false,
		//	callback: function () {
		//		//myText.hide();
		//	}
		//};

		//myText.show(newOptions);
	});

	$(window).on('load', function () {
		var textWrapper = document.querySelector('.ml2');
		textWrapper.innerHTML = textWrapper.textContent.replace(/\S/g, "<span class='letter'>$&</span>");

		anime.timeline({
			loop: false,
		})
		  .add({
		  	targets: '.ml2 .letter',
		  	scale: [4, 1],
		  	opacity: [0, 1],
		  	translateZ: 0,
		  	easing: "easeOutExpo",
		  	duration: 950,
		  	delay: (el, i) => 70 * i,
		  }).add({
		  	targets: '.ml2',
		  	opacity: 1,
		  	duration: 1000,
		  	easing: "easeOutExpo",
		  	delay: 1000
		  });

	})

</script>

WordsAndSynonyms/Views/Shared/Search.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	<script src="~/Dependencies/js/jquery-3.4.1.min.js"></script>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="~/Dependencies/materialize/css/materialize.css" rel="stylesheet" />
</head>
<body>
	@RenderBody()
	<script src="~/Dependencies/materialize/js/materialize.js"></script>
</body>
</html>

WordsAndSynonyms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Search", "Index", "Search")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>